examples/001-startup-global/global-hooks/hook.sh
examples/101-module-sysctl-tuner/modules/001-sysctl-tuner/hooks/module-hooks.sh
examples/201-sysctl-tuner-values/modules/001-sysctl-tuner/hooks/module-hooks.sh

examples: configVersion v1 for hooks

---

go.mod
go.sum

- shell-operator update https://github.com/flant/shell-operator/pull/116

fix: search gvr by kind

---

go.mod
go.sum
pkg/addon-operator/operator.go
pkg/app/debug-cmd.go
pkg/module_manager/module_manager.go

- add module label for logs of ModuleHookRun tasks
- add binding info for hook run tasks
- relabel when GlobalHookRun triggers a CreateReloadAll

fix: labels for json logs

---

pkg/utils/values.go
pkg/utils/values_test.go

feat: load json patch from file as a json stream of patch operations

---

go.mod
go.sum
pkg/addon-operator/operator.go
pkg/module_manager/hook.go

- module hook registration restarts from module with error
- add task fail description to queue dump

fix: module run restart

---

go.mod
go.sum

https://github.com/flant/shell-operator/pull/136

fix: mutex for GetExistingObjects in ResourceMonitor

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml
Dockerfile
Dockerfile-alpine3.10
Dockerfile-alpine3.9
go-build.sh
go.mod
go.sum
pkg/addon-operator/operator.go
pkg/helm_resources_manager/helm_resources_manager_test.go

fix: update libjq-go for better performance

---

go.mod
go.sum

related PR: https://github.com/flant/shell-operator/pull/164

feat: executeHookOnSynchronization for kubernetes bindings

---

pkg/addon-operator/operator.go
pkg/module_manager/module_manager.go

fix: codespell errors

---

pkg/addon-operator/operator.go

`/ready` endpoint returns 500 until the main queue has no "converge" tasks:
- ModuleRun, ModuleDelete, ModulePurge
- Reload*, Discover*
- GlobalHookRun for BeforeAll and AfterAll
This endpoint can be used as a readiness probe.

feat: endpoint for readiness probe

---

pkg/addon-operator/operator.go

Change readiness calculation: the 'main' queue is iterated after each task handling.

fix converge status and ready endpoint

---

pkg/addon-operator/operator.go
pkg/helm/helm.go
pkg/helm/helm_test.go
pkg/helm/tiller.go

fix: choose random ports for tiller if ports are in use

---

go.mod
go.sum
pkg/addon-operator/operator.go
pkg/helm/tiller.go
pkg/module_manager/global_hook.go
pkg/module_manager/hook.go
pkg/module_manager/module.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_manager.go
pkg/module_manager/module_manager_test.go
pkg/task/hook_metadata.go
pkg/task/task.go

Execute Synchronization for `kubernetes` hooks in parallel if queue is defined. 
_Fixes #111_

feat: parallel synchronization

---

.github/workflows/dev-build.yaml
.github/workflows/release-build.yaml
Dockerfile
Dockerfile-alpine3.11
Dockerfile-alpine3.9
cmd/addon-operator/main.go
go.mod
go.sum
pkg/addon-operator/operator.go

Alpine3.11 build with updated helm and kubectl

fix: replace zombie reaper with tini. Add alpine3.11 build

---

go.mod
go.sum

- fix problems with submodules

fix: update libjq-go

---

go.sum
pkg/addon-operator/operator.go
pkg/kube_config_manager/kube_config_manager.go
pkg/module_manager/global_hook.go
pkg/module_manager/module.go
pkg/module_manager/module_manager.go
pkg/task/hook_metadata.go
pkg/utils/module_config.go
pkg/utils/values.go

- recognize *Enabled paths in patches from global hooks
- add ReloadAll task if enabled modules set is changed
- fix tracing

feat: enable modules from global hooks

---

METRICS.md
go.mod
go.sum
pkg/addon-operator/metrics.go
pkg/addon-operator/operator.go

- reset queuedAt for failed HookRun task for correct results in task_wait_in_queue
- update metric descriptions

fix: snapshot_size description, fix wait_in_queue

---

go.mod
go.sum
pkg/addon-operator/operator.go
pkg/app/app.go
pkg/module_manager/global_hook.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_manager.go

- same as prometheus-listen-port by default
See https://github.com/flant/shell-operator/pull/190

feat: separate port for hook metrics

---

pkg/addon-operator/operator.go
pkg/app/debug-cmd.go
pkg/module_manager/module.go

feat: add module render debug command

---

.github/workflows/code-checks.yaml
.gitignore
examples/700-go-hook/README.md
examples/700-go-hook/global-hooks/global-go-hook.go
examples/700-go-hook/modules/001-module-go-hooks/hooks/go_hooks.go
examples/700-go-hook/register_go_hooks.go.tpl

Example of a highly experimental feature introduced in #143

example: go hooks

---

examples/001-startup-global/Dockerfile
examples/101-module-sysctl-tuner/Dockerfile
examples/201-sysctl-tuner-values/Dockerfile
examples/700-go-hook/README.md
examples/700-go-hook/global-hooks/global-go-hook.go
examples/700-go-hook/modules/001-module-go-hooks/hooks/go_hooks.go
sdk/sdk.go

fix: MainHandler now always default in go hooks

---

pkg/helm/helm.go
pkg/kube_config_manager/kube_config_manager.go
pkg/kube_config_manager/kube_config_manager_test.go

- checksums in annotation prevent GlobalChanged event in some cases

fix: get rid of annotation with checksums

---

METRICS.md
go.mod
go.sum
pkg/addon-operator/metrics.go
pkg/module_manager/global_hook.go
pkg/module_manager/hook_executor.go
pkg/module_manager/hook_executor_test.go
pkg/module_manager/module.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_manager.go

- sys and user cpu seconds
- max rss bytes

feat: usage metrics for hooks and enabled script

---

go.sum
pkg/addon-operator/operator.go
pkg/addon-operator/operator_test.go

This MR fixes the race condition in ModuleRun tasks handling.

fix: do not count the first task as a task from queue

---

pkg/module_manager/module.go
pkg/module_manager/module_manager.go
pkg/module_manager/module_manager_test.go
pkg/module_manager/testdata/load_values__module_apply_defaults/config_map.yaml
pkg/module_manager/testdata/load_values__module_apply_defaults/global-hooks/openapi/config-values.yaml
pkg/module_manager/testdata/load_values__module_apply_defaults/global-hooks/openapi/values.yaml
pkg/module_manager/testdata/load_values__module_apply_defaults/modules/000-module-one/openapi/config-values.yaml
pkg/module_manager/testdata/load_values__module_apply_defaults/modules/000-module-one/openapi/values.yaml
pkg/module_manager/testdata/load_values__module_apply_defaults/modules/values.yaml
pkg/module_manager/values_defaulting_transformers.go

Final fix for ApplyDefaults
Properly apply defaults for module values, for global values. Also, apply defaults for config values ($CONFIG_VALUES_PATH).
No
```release-note
```

fix: finally working ApplyDefaults for global and module values

---

VALUES.md
pkg/module_manager/global_hook.go
pkg/module_manager/hook.go
pkg/module_manager/module.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_manager.go
pkg/module_manager/module_manager_test.go
pkg/module_manager/utils.go
pkg/module_manager/values_defaulting_transformers.go
pkg/values/validation/defaulting_test.go
pkg/values/validation/extend_test.go
pkg/values/validation/required_test.go
pkg/values/validation/schema/additional-properties.go
pkg/values/validation/schema/copy.go
pkg/values/validation/schema/extend.go
pkg/values/validation/schema/required-for-helm.go
pkg/values/validation/schema/transform.go
pkg/values/validation/schemas.go
pkg/values/validation/schemas_test.go
pkg/values/validation/validator.go
pkg/values/validation/validator_test.go

Revert defaulting for config values.
`$CONFIG_VALUES_PATH` file should contain only ConfigMap content to hook be able to create proper config patches.
No
```release-note
```

fix: remove defaulting from config values

---

pkg/values/validation/defaulting_test.go
pkg/values/validation/schema/additional-properties.go
pkg/values/validation/schemas.go
pkg/values/validation/validator_test.go

Set `additionalProperties: false` recursively.
```release-note
```

fix: set additionalProperties to false recursively

---

go.mod
go.sum
pkg/addon-operator/operator.go
pkg/module_manager/global_hook.go
pkg/module_manager/hook_executor.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_hook_config.go
pkg/module_manager/module_manager.go

Kubernetes object manipulation

---

pkg/module_manager/global_hook_config.go
pkg/module_manager/go_hook/go_hook.go

This PR introduces the forgotten Settings field from the shell-operator.
```release-note
NONE
```

Added Settings field to the GoHook's HookConfig

---

pkg/module_manager/go_hook/patchable_values.go

Check that path exists on Values deletion
Check if path exists before deletion. If you call Remove
on absent path - it leads to error. Avoid this case
None

Improve PatchableValues Remove

---

go.mod
go.sum
pkg/addon-operator/kube_client.go
pkg/addon-operator/operator.go
pkg/addon-operator/operator_test.go
pkg/helm/helm.go
pkg/helm/helm2/helm2.go
pkg/helm/helm3/helm3.go
pkg/helm/helm_test.go
pkg/helm_resources_manager/helm_resources_manager.go
pkg/helm_resources_manager/helm_resources_manager_test.go
pkg/helm_resources_manager/resources_monitor.go
pkg/helm_resources_manager/types/types.go
pkg/kube_config_manager/kube_config_manager.go
pkg/kube_config_manager/kube_config_manager_test.go
pkg/module_manager/module.go
pkg/module_manager/module_manager.go
pkg/module_manager/module_manager_test.go

Use latest shell-operator
```release-note
```

refactor: use flant/kube-client library

---

go.mod
go.sum
pkg/module_manager/global_hook.go
pkg/module_manager/go_hook/go_hook.go
pkg/module_manager/hook.go
pkg/module_manager/hook_executor.go
pkg/module_manager/module_hook.go

Update shell-operator, use PatchCollector
```release-note
```

ref: object patcher

---

pkg/helm/helm3lib/helm3lib.go
pkg/helm_resources_manager/resources_monitor.go

Just cosmetic clean up after last changes
Make the code a bit more beautiful :)
NONE
```release-note
```

Some cosmetic changes to helm3lib

---

pkg/helm/helm3lib/helm3lib.go

Fix helm3 pending state
If helm release has only 1 revision it could not be rollbacked. Uninstall it then
NONE
```release-note
```

[helm3] uninstall first revision in pending state

---

.github/workflows/publish-dev.yaml
.github/workflows/publish-latest.yaml
.github/workflows/publish-release.yaml
.github/workflows/tests.yaml

github-script v5 use updated octokit, so replace github.issues -> github.rest.issues
```release-note
```

ref(ci): update github-script to v5

---

go.mod
go.sum

- fix: Add more info about failed patcher operations (#332)
- fix: always return non 'already exists' error for Create operation (#331)
```release-note
```

chore(deps): update shell-operator to latest 2021-11-11

---

pkg/module_manager/global_hook.go
pkg/module_manager/module.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_manager.go

ModuleManager component stores caches with values and patches. This PR fixes the race when these caches update from parallel queues.
```release-note
```

fix: enable locks for updating caches in ModuleManager.

---

go.mod
go.sum

Update shell-operator to latest release
```release-note
```

chore(deps): bump shell-operator to 1.0.5

---

.github/workflows/build.yaml
.github/workflows/publish-dev.yaml
.github/workflows/publish-latest.yaml
.github/workflows/publish-release.yaml
.github/workflows/tests.yaml
go.sum

chore(ci): rename master to main in refs

---

pkg/addon-operator/operator.go
pkg/module_manager/module.go

Modules are long-lived objects, but Synchronization state is not cleaned when disable module. This situation leads to a race: a hook executes while module is already disabled and empty values are set. When module enables, no Synchronization done and Helm runs with empty values.
```release-note
```

fix: clean module state when disabled

---

go.mod
go.sum

Update shell-operator to 1.0.6
```release-note
```

deps: update shell-operator to 1.0.6

---

go.mod
go.sum
pkg/addon-operator/operator.go
pkg/app/debug-cmd.go
pkg/module_manager/global_hook.go
pkg/module_manager/hook.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_manager.go
pkg/task/hook_metadata.go

Add more commands for diagnostic.
Commands:
- 'global snapshots' to get snapshots for all global hooks
- 'module snapshots module-name' to get snapshots for one module
- 'global list' to get all global hooks names
- 'queue main' to dump tasks in the main queue
```release-note
```

feat: more debug commands

---

Dockerfile

Synchronize with shell-operator:
- Use alpine 3.15.
- Use kubectl 1.21.10.
- Use frameworks from shell-operator 1.0.9
Synchronize with helm dependency:
- Use helm 3.5.4.
Update tools to more recent versions before release.
```release-note
```

chore: update versions in Dockerfile

---

pkg/helm/helm3lib/helm3lib.go

Reinitialize kubeClient on helm3lib upgrade
Cached kubeClient on helm3lib upgrade can miss some validation cases like Feature Gates. We have to reinitialize it for successful validation.
NONE
```release-note
```

reinitialize kubeClient

---

go.mod
go.sum

shell-operator updated to latest.
Map write race prevented in https://github.com/flant/shell-operator/pull/408
```release-note
```

[chore] update shell-operator

---

cmd/addon-operator/main.go
pkg/addon-operator/bootstrap.go
pkg/addon-operator/operator.go

This is a supplemental feature for config conversions in deckhouse.
Use external initial config to bypass config validation in ModuleManager at start.
```release-note
```

feat: override KubeConfig before bootstrap

---

pkg/values/validation/validator.go

Mainly for deckhouse. There should access to schemas to apply default values before validate settings.
See https://github.com/deckhouse/deckhouse/pull/3206

feat: GetSchema method in ValuesValidator

---

go.mod
go.sum

Signed-off-by: Ivan Mikheykin <ivan.mikheykin@flant.com>
Use shell-operator 1.1.1 
https://github.com/flant/shell-operator/compare/v1.0.12...v1.1.1
```release-note
```

chore: update shell-operator to 1.1.1

---

go.mod
go.sum

Update shell-operator to add watch error handler.
See https://github.com/flant/shell-operator/pull/447

feat: add watch error handler

---

pkg/addon-operator/bootstrap.go
pkg/addon-operator/operator.go
pkg/addon-operator/operator_test.go
pkg/kube_config_manager/kube_config_manager.go
pkg/kube_config_manager/kube_config_manager_test.go
pkg/module_manager/global_hook.go
pkg/module_manager/go_hook/go_hook.go
pkg/module_manager/hook.go
pkg/module_manager/hook_executor_test.go
pkg/module_manager/module.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_manager.go
pkg/module_manager/module_manager_test.go

- Remove unnecessary interfaces
- Configure structs with config, not with separate methods
- Remove unused code
- Simplify methods calls
Just a cleanup for easy code navigation
NONE
```release-note
```

Refactor module-manager

---

pkg/module_manager/module_loader.go

Don't fall with a fatal error on an absent symlink
Multi-master installation could have broken symlinks. We should start anyway, just ignore broken module.
NONE
```release-note
```

Ignore module on absent symlink

---

pkg/addon-operator/converge.go
pkg/addon-operator/operator.go

Remove dot imports
Dot imports are not obvious and make a code confusing
NONE
```release-note
```

More refactoring

---

pkg/addon-operator/debug_server.go
pkg/app/debug-cmd.go
pkg/helm/client/client.go
pkg/helm/helm3/helm3.go
pkg/helm/helm3lib/helm3lib.go
pkg/helm/test/mock/mock.go
pkg/module_manager/module.go

Add debug flag for render command
Sometimes rendering helm chart fails and error can't help with debugging. Debug flag can help with this
```release-note
Add debug flag for render command
```

feat: Add debug flag for render command

---

go.mod
go.sum
pkg/utils/values.go

Use  more popular more performant lib that is used by popular projects such as Kubernetes
```
goos: darwin
goarch: amd64
pkg: github.com/flant/addon-operator/pkg/utils
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkMarge/merge-12                      936           1205171 ns/op          769262 B/op      11710 allocs/op
BenchmarkMarge/mergo-12                     2169            584595 ns/op          128480 B/op       5552 allocs/op
```
```release-note
Use mergo to merge values.
```

feat: use mergo to merge values

---

cmd/addon-operator/main.go
pkg/addon-operator/bootstrap.go
pkg/addon-operator/debug_server.go
pkg/addon-operator/http_server.go
pkg/addon-operator/operator.go
pkg/addon-operator/operator_test.go

Move global functions to addon-operator methods
Remove `Bootrap()` separate call, integrate it to the `Start()` call
Integrate `Bootsrap()` function into the `Start()` method
```release-note
Optimize addon-operator methods
```

Addon-operator method calls

---

pkg/helm_resources_manager/resources_monitor.go

To check absent resources, use the kube-apiserver cache. It will reduce the amount of traffic between kube-apiserver and etcd and should reduce the kube-apiserver pressure.|
https://kubernetes.io/docs/reference/using-api/api-concepts/#semantics-for-get-and-list
Objects in a release can be deployed to many different namespaces. For example, if the module is deployed within namespace with many secrets, e.g., helm secrets, addon-operator will constantly request them from etcd.
Idle cluster difference
kube-apiserver ~400mb
etcd ~100mb (there is not much difference because there are not so many CRDs in the cluster)

Read resources from cache in resource monitor

---

go.mod
go.sum
pkg/module_manager/module_manager.go
pkg/utils/values.go

Revert https://github.com/flant/addon-operator/pull/380

Revert mergo lib

---

docs/src/HOOKS.md
docs/src/LIFECYCLE.md
docs/src/OVERVIEW.md
docs/src/README.md
docs/src/RUNNING.md
docs/src/VALUES.md
docs/src/metrics/SELF_METRICS.md

- external links to dedicated list
- apply fixes to links
This PR fixes links in auto-generated doc.
--

Fix links in the doc after migration

---

README.md
docs/src/README.md

Clean up tiller mentions from docs
Just housekeeping

Clean up tiller mentions from docs

---

pkg/addon-operator/operator.go
pkg/module_manager/module_manager.go
pkg/module_manager/module_manager_test.go

Add ability to explicitly set purge modules
After disabling automatic purge for modules we can have stuck modules. We can add a mechanism to explicitly set modules to purge

[fix] Modules purge

---

pkg/app/app.go
pkg/module_manager/module_loader.go

Add strict check mode for MODULE_DIR/values.yaml files
Because missing MODULE_DIR/values.yaml  can be destructive.

Add strict check mode for MODULE_DIR/values.yaml files

---

go.mod
go.sum

Updated dependency
https://github.com/deckhouse/deckhouse/issues/6548
More details: https://github.com/flant/go-openapi-validate/commit/232e994bd2a62215b9638d58671971e731835314

fixed division by zero during module validation

---

pkg/module_manager/models/modules/global.go
pkg/module_manager/module_manager.go

Inject `enabledModules` key to the global values
Restore compatibility. At not modules from sources are not injected into values

Fix enabled modules

---

pkg/module_manager/module_manager.go

Don't create channel on startup
We want to create the channel and write to it only if someone reads it
Closes #436

Fix modules events channel

---

pkg/module_manager/models/modules/global.go

EnabledModule should not be sorted
It breaks the original modules order

remove sort

---

cmd/addon-operator/main.go

Added logs before os.Exit(1) with error in main.go
If you use the operator as is and do not add the /global-hooks directory to the image, the code exits with exit code 1 without any error messages.

Added logs before os.Exit(1) in main.go

---

pkg/module_manager/module_manager.go

We don't have to replace enabled modules from helm releases
This behavior was created for previous iterations. We run this function after first converge, so we have to calculate enabled modules here

Remove enabledModules replace

---

pkg/module_manager/module_manager.go

Have to figure out rare panic
In some cases we have a panic which is hard to understand. Need to add debug info for function which generates the panic

add panic debug

---

pkg/addon-operator/converge/converge.go
pkg/addon-operator/http_server.go
pkg/addon-operator/operator.go
pkg/addon-operator/operator_test.go
pkg/addon-operator/queue.go
pkg/module_manager/loader/fs/fs.go
pkg/module_manager/loader/loader.go
pkg/module_manager/models/modules/events/events.go
pkg/module_manager/module_manager.go

*Some refactoring of the code related to registering a module (load/reload) so as to make it bit more straightforward and unambiguous.
*Module registration/load leverages ConvergeModules (ReloadAllModules) functionality of the operator in case a new module has to be registered.
*Converge-related code has been moved from addon_operator packege to a dedicated converge package so that it could be used by module manager package.
Besides some refactoring, this PR introduces another approach to module registration: if a new module is registered in enabled state, instead of reloading the operator we run ConvergeModules task that reloads all enabled modules so that their values are updated in accordance with the new configuration.

some refactoring

---

pkg/addon-operator/bootstrap.go
pkg/addon-operator/debug_server.go
pkg/addon-operator/operator.go

The changes are described and tested in the context of [deckhouse PR](https://github.com/deckhouse/deckhouse/pull/7982)
Allows access to the "debug srv" object

Cli command to show requirements

---

pkg/module_manager/loader/fs/fs.go
pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/values_storage.go
pkg/module_manager/module_manager.go

- Fixed LoadModule() logic (previously, it didn't load static values from the module's parent directory);
- RunModuleWithNewStaticValues method is introduced to renew the module's static values and recalculate resulting values of the module;
- Additional methods for BasicModule are added: to get the module's static values and to set(and recalculate) resulting values;
- PushRunModuleTask method is updated and it is possible to define if start-up hooks should be run on the module's run.
In two words, this PR provides additional API to work with modules' static values so as not only do a module's static values get set on the operator's startup, but they also can be updated and recalculated later. 
Relates to https://github.com/deckhouse/deckhouse/pull/8067

Provide a way of updating a module's static values

---

pkg/values/validation/schemas.go

fix error message

---

pkg/addon-operator/operator.go

This pr updates ManagerEventHandler logic in terms of preventing the graph's recalculation if the operator hasn't reached ConvergeModules tasks yet as it may interfere with running global hooks, resulting in a stuck queue.
This pr update adds more conditional to make the operator's bootstrap process more robust.

update module manager event handler

---

go.mod
go.sum
pkg/module_manager/models/hooks/dependency.go
pkg/module_manager/models/hooks/kind/gohook.go
pkg/module_manager/models/hooks/kind/shellhook.go
pkg/module_manager/models/hooks/module_hook.go
pkg/task/hook_metadata.go

Bump shell-operator

---

go.mod
go.sum

Fixed logrus memory leak
It fixes the logrus [memory leak](https://github.com/flant/shell-operator/issues/653)

[chore] bump shell operator

---

pkg/addon-operator/ensure_crds.go

Considering that etcd has a default value of 1.5Mb, it was decided to set it to 2Mb, so that in most cases we would get a more informative error from Kubernetes, not just "short buffer"
You shouldn't delete the branch after the merge, because it is used to build deckhouse 1.65

Increased CRDs Installer buffer size

---

.golangci.yaml
go.mod
go.sum
pkg/addon-operator/kube_client.go
pkg/addon-operator/operator.go
pkg/kube_config_manager/backend/configmap/configmap.go
pkg/kube_config_manager/config/config.go
pkg/kube_config_manager/kube_config_manager_test.go

rename log label field key source in event_source to not override original source
it makes log clear

[addon-operator] fix/rename source field

---

pkg/addon-operator/ensure_crds.go

Abstracted the kubernetes client for use in tests

Improved CRDs Installer

---

pkg/module_manager/models/modules/basic.go

change batch hook name

---

pkg/module_manager/loader/fs/fs.go
pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/basic_test.go

rollback to global values in constructors

---

pkg/module_manager/go_hook/go_hook.go

Replace patch values in go hook structure with interface, make using gohook more flexible
Replace patch values with interface

replace patchvalues with interface

---

pkg/addon-operator/converge/converge.go

Consider ModuleEnsureCRDs tasks as converge tasks so that such tasks are getting deleted if converge has to restart.

consider ModuleEnsureCRDs tasks as converge tasks

---

pkg/module_manager/models/hooks/kind/batch_hook.go

Add version to config in batch hook

[batch-hook] fix version bug

---

pkg/addon-operator/debug_server.go
pkg/module_manager/module_manager.go
pkg/module_manager/scheduler/scheduler.go

Register graph handler without wrapper
We can get a graph as png
Also we can specify `?format=text` and get the DOT description which could be useful to debug in graphviz online

Add graph text description handler

---

pkg/module_manager/scheduler/extenders/mock/extenders_mock.go
pkg/module_manager/scheduler/node/mock/node_mock.go
pkg/module_manager/scheduler/node/node.go
pkg/module_manager/scheduler/scheduler.go
pkg/module_manager/scheduler/scheduler_test.go

Fixes the order the graph's vertices are run against applied extenders.
Adds "depth" labels to the graph's edges to understand the sequence modules are run in.

[scheduler] fix out of order vertices traversing

---

go.mod
go.sum

[addon-operator] bump shell operator

---

pkg/helm/helm_test.go
pkg/helm/version_detect.go
pkg/helm/version_detect_test.go

Make helm3lib by default

---

pkg/helm/helm3/helm3.go
pkg/helm/helm3lib/helm3lib.go

- Correction of variadic argument expansion in the log formatting function.
- Removal of the "Force" flag from the upgrade configuration in pkg/helm/helm3lib/helm3lib.go.
- Removal of the "--force" argument from the upgrade command in pkg/helm/helm3/helm3.go.
Force flag is too tough. It breaks a lot of kubernetes resources

Rollback force flag

---

pkg/addon-operator/operator.go
pkg/kube_config_manager/backend/configmap/configmap.go
pkg/kube_config_manager/config/config.go
pkg/kube_config_manager/kube_config_manager.go
pkg/kube_config_manager/kube_config_manager_test.go
pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/helm.go
pkg/module_manager/module_manager.go
pkg/utils/module_config.go

refactor: rename ManagementState to MaintenanceState across the module

---

pkg/task/module-run/task.go

Fix ModuleRun response. It not skip Fail status.

module run response fail fix

---

pkg/task/discover-crds/service.go
pkg/task/module-ensure-crds/task.go
pkg/task/service/service.go

Now we save all crds from all tasks

[addon-operator] fix crd discoverer

---

pkg/utils/module_config.go

It fixes default maintenance state.

[fix] fix maintenance default value

---

pkg/utils/module_config.go

It fixes default maintenance value

[fix] 1.7 maintaince state

---

pkg/module_manager/go_hook/filter_result.go
pkg/module_manager/go_hook/filter_result_test.go

[addon-operator] 1.9 Add verbosity to unmarshal error

---

go.mod
go.sum
pkg/addon-operator/handler_manager_events.go
pkg/addon-operator/operator.go
pkg/addon-operator/operator_test.go
pkg/addon-operator/queue_test.go
pkg/task/queue/utils.go
pkg/task/service/service.go
pkg/task/tasks/converge-modules/task.go
pkg/task/tasks/global-hook-enable-kubernetes-bindings/task.go
pkg/task/tasks/module-run/task.go

Bump shell-operator
Using new options pattern
Using new re-generate task UUID mechanism
Add compactionID mechanism to combine same tasks under the hood

[addon-operator] fix queue compaction
