go.sum
pkg/addon-operator/operator.go
pkg/task/module_hook_metadata.go

Now it is possible to tell why task was queued:
Restart of DiscoverModulesState on global values change by afterAll hooks:
```
GlobalHookRun:main:beforeAll:v1-hook-beforeall.sh:AfterAllHooksChangeGlobalValues
GlobalHookRun:main:beforeAll:v1-hook-kube.sh:AfterAllHooksChangeGlobalValues
DiscoverModulesState:main:::AfterAllHooksChangeGlobalValues
```
Module reload on values changes by afterHelm while processing DiscoverModulesState triggered by global values changes :open_mouth: :
```
ModuleRun:main::module-reload:GlobalValuesChanged.DiscoverModulesState.AfterHelmHooksChangeModuleValues
```
ModuleRun on absent resources detected:
```
ModuleRun:main::big-chart:DetectAbsentHelmResources
```
A batch of hooks with similar apiVersion and kind in kubernetes bindings:
``` …
```

fix: queue dump: add description for event that triggered a task

---

pkg/addon-operator/operator.go
pkg/module_manager/global_hook.go
pkg/module_manager/hook_executor.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_manager.go
pkg/utils/metrics.go

New temporary file $METRIC_PATH can be filled with JSON objects that
desribe operations with prometheus metrics. The Addon-operator parses
this file and publish metrics via /metrics endpoint.
Example:
cat <<EOF >> $METRICS_PATH
{"name":"metric_gauge", "set":34.12, "labels":{"label1":"val1", ... }}
{"name":"metric_count", "add":1, "labels":{"label1":"val1", ... }}
EOF
These JSON objects become these metrics:
metric_gauge{"hook":"hook.sh", "label1":"val1"} 34.12
metric_count{"hook":"hook.sh", "label1":"val1"} 1
The Addon-operator adds labels to metrics: "hook" and "module" for
metrics from module hooks and "hook" for metrics from global hooks.
_This PR relates to issue in shell-operator_ https://github.com/flant/shell-operator/issues/130

feat: initial support for metrics from hooks

---

pkg/helm/helm.go
pkg/helm/tiller.go

- default timeout was 300s, set it to 2s.
- timeout of tiller waiting process is 10s.

fix: add --tiller-connection-timeout for `helm version` command

---

pkg/addon-operator/operator.go
pkg/helm/tiller.go

fix: remove 'output' label for tiller subprocess logs

---

cmd/addon-operator/main.go
go.mod
go.sum
pkg/addon-operator/operator.go
pkg/helm_resources_manager/helm_resources_manager.go
pkg/module_manager/hook_executor.go
pkg/module_manager/module.go

- feat: observability for hooks, queues, Kubernetes events handling
- feat: cleaner for metrics from hooks 
- fix: run helm upgrade even if no Synchronization tasks are queued
- fix: wait for queues on exit
- fix: informer go routines leakage on ReloadAllModules
See https://github.com/flant/shell-operator/pull/176

Cumulative update: observability, metrics cleaner and fixes

---

go.mod
go.sum
pkg/addon-operator/operator.go
pkg/kube_config_manager/kube_config_manager.go
pkg/module_manager/global_hook.go
pkg/module_manager/hook.go
pkg/module_manager/module.go
pkg/module_manager/module_manager.go
pkg/module_manager/module_manager_test.go
pkg/module_manager/testdata/discover_modules_state__module_names_order/config_map.yaml
pkg/module_manager/testdata/discover_modules_state__simple/config_map.yaml
pkg/module_manager/testdata/discover_modules_state__with_enabled_scripts/config_map.yaml
pkg/module_manager/testdata/discover_modules_state__with_enabled_scripts/modules/003-gamma/enabled
pkg/module_manager/testdata/discover_modules_state__with_enabled_scripts/modules/004-delta/enabled
pkg/module_manager/testdata/discover_modules_state__with_enabled_scripts/modules/006-zeta/enabled
pkg/module_manager/testdata/get__module_hooks_in_order/config_map.yaml
pkg/task/hook_metadata.go
pkg/utils/module_config.go
pkg/utils/module_list.go
pkg/utils/values.go

feat: keepFullObjectsInMemory for kubernetes binding contexts
- add hook, binding and module labels for _kube_jq_hist metric
feat: enable modules from global hooks
- recognize *Enabled paths in patches from global hooks
- queue ReloadAll task if enabled modules set is changed
- properly disable modules without the Helm release
*See #130*

feat: full object in snapshot

---

go.mod
go.sum

- feat: group and includeSnapshotsFrom are now compatible
- docs: describe group and includeSnapshotsFrom
- fix: sorting in snapshots and objects when `keepFullObjectsInMemory: false`
See https://github.com/flant/shell-operator/pull/179
- fix(jq): catch compile errors. See https://github.com/flant/libjq-go/pull/16

update shell-operator: snapshots, jq errors

---

pkg/module_manager/module.go

```
Metric histogram observe deckhouse_module_hook_run_seconds [activation binding hook module] with map[activation: binding:afterHelm hook:hook-name module:module-name]: inconsistent label cardinality: expected 5 label values but got 4 in prometheus.Labels{\"activation\":\"\",
\"binding\":\"afterHelm\", \"hook\":\"hook-name\", \"module\":\"module-name\"}"
```

fix: inconsistent label cardinality

---

pkg/addon-operator/operator.go

Fix counter metric behavior for gauge metric `tasks_queue_length`.

fix: use set method to fill tasks_queue_length gauge metric

---

pkg/addon-operator/operator.go
pkg/app/app.go
pkg/helm/client/client.go
pkg/helm/helm.go
pkg/helm/helm2/helm2.go
pkg/helm/helm2/tiller.go
pkg/helm/helm3/helm3.go
pkg/helm/helm_mock.go
pkg/helm/helm_test.go
pkg/helm_resources_manager/helm_resources_manager.go
pkg/helm_resources_manager/resources_monitor.go
pkg/module_manager/module.go
pkg/module_manager/module_manager_test.go

- if helm 3 is in path, use it to manage module charts
- --helm-history-max and --helm-timeout flags for upgrade operation
- fix namespace in module resource-monitor output
- reduce helm history executions

feat: helm3 compatibility

---

.github/workflows/build.yaml
.github/workflows/dev-build.yaml
.github/workflows/lint.yaml
.github/workflows/release-build.yaml
.github/workflows/tests.yaml
RUNNING.md
go.sum
pkg/helm/helm.go
pkg/helm/helm2/helm2.go
pkg/helm/helm2/tiller.go
pkg/helm/helm3/helm3.go
pkg/helm/version_detect.go
pkg/helm/version_detect_test.go

Use "helm --help" to detect helm 2. Add environment variables to override helm and tiller paths and to set helm version compatibility.

fix: detection of helm version

---

pkg/helm/helm3/helm3.go

fix code comment typo for `helm3` func `Render`
PTAL
/cc @diafour

fix: fix typo of helm3 Render comment

---

go.mod
go.sum

Update shell-operator version with fix https://github.com/flant/shell-operator/issues/218

fix: exponential backoff panic

---

pkg/addon-operator/operator.go
pkg/module_manager/module.go

Remove `values.yaml` files from a tmp dir after installing a module.
Addon-operator accumulates values files making the tmp folder to burst.
It makes difference when you trigger module reinstallation frequently.
```
root@kube-master / # du -sh /tmp/addon-operator/
140M	/tmp/addon-operator/
root@kube-master /# ls /tmp/addon-operator/ | grep values | wc -l
5979
```
It's more about internal mechanics.
```release-note
cleanup helm values after upgrading a module 
```

fix: cleanup helm values after upgrading a module

---

pkg/module_manager/module.go
pkg/module_manager/module_manager.go

Add AplyDefaults to module values
Defaults from openapi schemas were applied only to global values.
No
```release-note
```

fix: add ApplyDefaults for module values

---

HOOKS.md
RUNNING.md
go.mod
go.sum
pkg/addon-operator/operator.go
pkg/app/app.go
pkg/helm/helm3/helm3.go
pkg/module_manager/global_hook.go
pkg/module_manager/module.go
pkg/module_manager/module_hook.go

Bring in execution rate settings from shell-operator: https://github.com/flant/shell-operator/pull/257.
Add `HELM_IGNORE_RELEASE` option to not treat the addon-operator release as a module.
1. Addon-operator can combine tasks in the queue and run the hook once with an array of binding contexts. Execution rate settings help to handle multiple events that are occurred during a short period.
2. `HELM_IGNORE_RELEASE` prevents self-destcruction in setup where addon-operator release is stored in the same namespace as modules (`ADDON_OPERATOR_NAMESPACE`).
```release-note
```

feat: execution rate settings for hooks

---

RUNNING.md
pkg/addon-operator/operator.go
pkg/app/app.go

Add a separate kube client for Helm resources monitor.
The addon-operator uses the same kube client for hook events and for Helm resources monitor. Helm resources monitor periodically lists all resources defined in Helm charts and kube client becomes rate limited. This PR adds new flags to set separate rate limit settings for Helm resources monitor.
```release-note
```

feat: use separate kube client for helm resources monitor

---

go.mod
go.sum
pkg/addon-operator/kube_client.go
pkg/addon-operator/operator.go

Add a 'component' label for metrics from kube clients.
```release-note
```

feat: component label to distinguish metrics from kube clients

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.md

Ask questions on the Github Discussions instead of Flant community site
We decided to switch to `discussions` because it already has all the necessary features
```release-note
```

fix: change forum link

---

go.sum
pkg/module_manager/global_hook.go
pkg/module_manager/module.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_manager.go
pkg/utils/values_patch.go
pkg/utils/values_patch_test.go

Ignore errors from 'remove' patch operations.
It is a common situation when config values contain a key, then hook returns a patch and removes this key. Lately, user edits a ConfigMap and also removes a key. Since then, the patch set is "poisoned" with the 'remove' operation of a nonexistent key.
```release-note
```

fix: ignore 'nonexistent path' errors from 'remove' patch operations

---

pkg/module_manager/global_hook_config.go

Only last Filterable is used:
```
Kubernetes: []go_hook.KubernetesConfig{
{
Name:                         "pods",
ApiVersion:                   "v1",
Kind:                         "Pod",
Filterable:                   &Fitlerable1{},
},
{
Name:                         "secrets",
ApiVersion:                   "v1",
Kind:                         "Secret",
Filterable:                   &SecretObject{},
},
},
```
```
1 *hooks.SecretObject *hooks.SecretObject
2 *hooks.SecretObject *hooks.SecretObject *hooks.SecretObject
```
```release-note
```

fix: go hook config converter

---

examples/700-go-hook/modules/001-module-go-hooks/hooks/go_hooks.go
pkg/module_manager/global_hook_config.go
pkg/module_manager/go_hook/go_hook.go
pkg/module_manager/test/go_hooks/global-hooks/simple.go
sdk/registry.go
sdk/sdk.go

1. Replaced Filterable with FilterFunc
2. Removed Register(), left only RegisterFunc()
3. Added helper function to convert to and from Unstructured objects
The Filterable interface is unwieldy and impossible to reason about. Replaced it with a simple function.
```release-note
NONE
```

Replaced Filterable with FilterFunc, also, some changes in the registry.go

---

pkg/module_manager/hook.go
pkg/module_manager/hook_executor_test.go
pkg/module_manager/module_manager_test.go
sdk/registry.go
sdk/test/sdk_test.go

Fix Name and Path fields for go hooks to be in line with shell hooks.
Each hook is registered with "Name" and "Path". "Name" is used as a hook identifier in shell-operator managers and "Path" is used for sorting binding with the same order (for completeness Path is also used to run shell hooks). Shell-operator managers are simple and know nothing about modules/global hooks. So we end up running the wrong hook if there are go hooks with the same file name but in different modules. This fix makes Name and Path for go hooks similar to shell hooks.
```release-note
```

fix: Name and Path in go hook metadata

---

sdk/sdk.go

Change type of the `obj` parameter to `interface{}`
Custom Resource struct may not implement runtime.Object and DefaultUnstructuredConverter not requires runtime.Object.
```release-note
```

fix: FromUnstructured not work for custom struct without DeepCopy implementation

---

pkg/helm/helm3lib/helm3lib.go

Remove unnecessary error when rolling back a release
This error is useless because we have a release upgrade immediately after a rollback. We don't care about rollback results. That behavior only leads to one more module restart during the error occurs
NONE
```release-note
```

remove unused error

---

pkg/module_manager/module_manager.go

Recursively call config validation
Metric `config_values_errors_total` should increase while config is invalid. We can add a validation flag and check it periodically  and increase the counter until the config is fixed
```release-note
NONE
```

Add recursive call for config validation and increase counter

---

cmd/addon-operator/main.go
go.mod
go.sum

Update shell-operator to v1.0.8
- FullTimestamp output for logrus color mode
- Ability to set log level to debug in runtime for a period of time.
```release-note
```

feat: runtime config from shell-operator

---

go.mod
go.sum
pkg/addon-operator/operator.go
pkg/module_manager/go_hook/go_hook.go

Revert starting schedule manager on start operator instead starting after first converge.
For go-hooks added flag `HookConfigSettings.EnableSchedulesOnStartup` for enable schedule hook without waiting finish converge.
By default all hooks (go and shell) will be running after converge. 
Some schedule hooks can run critical routines for operator (for ex, [deckhouse](https://github.com/deckhouse/deckhouse) uses them for auto-updating itself.)
Users can use schedule go-hooks before first converge.
```release-note
```

Add flag to start scheduling 'schedule' hook before first converge done.

---

pkg/addon-operator/operator.go
pkg/app/app.go
pkg/kube_config_manager/kube_config_manager.go
pkg/kube_config_manager/kube_config_manager_test.go
pkg/module_manager/module_manager_test.go

ValuesChecksumsAnnotation was used to store config values
cheksums in the annotation on the ConfigMap/addon-operator.
Later this mechanism is proved to be error-prone. Now it is
replaced with checksums fields in KubeConfigManager (#154).
Clean up code left after ValuesChecksumsAnnotation deletion.
```release-note
```

chore: remove unused ValuesChecksumsAnnotation

---

pkg/addon-operator/operator.go
pkg/module_manager/module_manager.go
pkg/task/task.go

AmbiguousState is an initial mechanism to self-heal after
errors in enabled scripts. Now there is a handler of this
state in AddonOperator, but ModuleManager not emit this
event anymore after 873f8026 (Nov 28 2018).
It is time to remove this code.
Cleanup unused code.
```release-note
```

chore: remove everything related to AmbiguousState

---

HOOKS.md
go.sum
pkg/addon-operator/operator.go
pkg/module_manager/global_hook.go
pkg/module_manager/go_hook/go_hook.go
pkg/module_manager/hook.go
pkg/module_manager/module.go
pkg/module_manager/module_hook.go
pkg/module_manager/module_manager.go
pkg/module_manager/module_manager_test.go
pkg/module_manager/module_state.go
pkg/module_manager/synchronization_state.go

- Queue Synchronization tasks for all hooks to properly enable monitors and events.
- Replace multiple module state flags with one phase.
- Move Synchronization state from hooks into module.
- Extract Synchronization state to the struct.
Now beforeHelm hook always got snapshots from all kubernetes binding beside executeHookOnSynchronization/waitForSynchronization settings.
```release-note
```

fix: beforeHelm hook got empty snapshots for some bindings

---

pkg/helm/helm3lib/helm3lib.go

Disable OpenAPI validation on manifest rendering
We need it to avoid some cases like FeatureGates changing during the operator lifetime. Install/Upgrade command also checks validation though this method (Render) can securely disable validation cause of only manifests checksum building
```release-note
NONE
```

Disable OpenAPI validation for manifests rendering in helm3lib

---

go.mod
go.sum

Restore separate metrics storage for hooks.
No metrics from hooks when separate port for hook metrics is in use after applying https://github.com/flant/shell-operator/pull/388 and #315.
```release-note
```

fix: restore separate metric storage for hooks

---

pkg/addon-operator/operator.go
pkg/addon-operator/queue.go
pkg/addon-operator/queue_test.go

Add message about left ModuleRun/ModuleDelete tasks to process during ConvergeModules.
Restore previous messages "N converge tasks after handle..." in a more predictable way.
Report only count of ModuleRun and ModuleDelete tasks emerged from ConvergeModules task.
```release-note
```

fix: report about modules left to process during the converge

---

pkg/addon-operator/debug_server.go
pkg/module_manager/module.go
pkg/module_manager/module_manager.go

Use getters with locks to get module values from ModuleManager.
Fix panic on module values access:
```
fatal error: concurrent map read and map write
goroutine 19695 [running]:
runtime.throw(0x2b4ea10, 0x21)
/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc007eea958 sp=0xc007eea928 pc=0x4432b2
runtime.mapaccess1_faststr(0x2626360, 0xc000877260, 0xc000cc22d7, 0x5, 0xc0117758c0)
/usr/local/go/src/runtime/map_faststr.go:21 +0x465 fp=0xc007eea9c8 sp=0xc007eea958 pc=0x41ed65
github.com/flant/addon-operator/pkg/module_manager.(*Module).Values(0xc000112e60, 0xc000cc22d7, 0x5, 0x0)
/go/pkg/mod/github.com/flant/addon-operator@v1.0.6-0.20220620123828-eaf343743c09/pkg/module_manager/module.go:741 +0x46b fp=0xc007eeab28 sp=0xc007eea9c8 pc=0x1a6b24b …
```

fix: concurrent map read-write on access module values

---

go.mod
go.sum
pkg/addon-operator/debug_server.go

- fix: namespace.labelSelector bindings
- fix: panic on access to snapshots
- fix: restore exponential backoff
- fix: restore separate metric storage
- fix(deps): bump go-chi to v5.0.7
Update shell-operator dependency to tagged version.

feat(deps): update shell-operator to v1.0.11

---

sdk/registry.go
sdk/registry_test.go

Forbid usage OnStartup and Kubernetes bindings together
Hook with onStartup binding could not have kubernetes snapshots. Usually ability to declare them together leads to logic errors. Let's forbid it.
NONE

forbid usage startup and kubernetes bindings together

---

go.mod
pkg/values/validation/schemas.go
pkg/values/validation/schemas_test.go
pkg/values/validation/testdata/test-schema-ok-project-2.yaml
pkg/values/validation/testdata/test-schema-ok-project.yaml

go-openapi/swag package uses yaml.MapSlice type to unmarshal from YAML bytes. This type supports 'direct' anchoring (`properties: *anchor`) but doesn't support 'map merge' (`<<: *anchor`). Additional loader is added to unmarshal YAML bytes into interface{}, so 'map merge' is now supported.
Add tests to check for anchor support and also check if $ref is working.
'map merge' is a convinient feature of YAML format, we use it in CRDs in deckhouse to copy and add properties between objects: [OpenStackClusterConfiguration](https://github.com/deckhouse/deckhouse/blob/main/ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml#L206)

fix: support 'map merge' feature for OpenAPI schemas in YAML files

---

go.mod
go.sum
pkg/addon-operator/converge.go
pkg/addon-operator/http_server.go
pkg/addon-operator/operator.go
pkg/module_manager/module_manager.go
pkg/module_manager/module_manager_test.go
pkg/module_manager/module_state.go
pkg/module_manager/testdata/load_and_validate_usage/global/hooks/hook
pkg/module_manager/testdata/load_and_validate_usage/global/openapi/config-values.yaml
pkg/module_manager/testdata/load_and_validate_usage/modules/000-test-module/hooks/hook
pkg/module_manager/testdata/load_and_validate_usage/modules/000-test-module/openapi/config-values.yaml

Supporting changes for https://github.com/deckhouse/deckhouse/pull/1729
- Prevent queueing ConvergeModules while running global hooks at startup
- Add tracking last error for ModuleRun, ModuleDelete and ModuleHookRun
- Add GetModuleNames method
Global hook in 1729 changes ConfigMap and premature KubeConfigChanged event breaks enabled modules state.
```release-note
```

fix: ignore KubeConfig events before first converge

---

Dockerfile

Update to alpine-3.15 leads to an error "'cannot find 'ld" during build.
```
#54 [linux/arm/v7 builder 9/9] RUN shellOpVer=$(go list -m all | grep shell-operator | cut -d' ' -f 2-)     CGO_ENABLED=1     CGO_CFLAGS="-I/libjq/include"     CGO_LDFLAGS="-L/libjq/lib"     GOOS=linux     go build -ldflags="-linkmode external -extldflags '-static' -s -w -X 'github.com/flant/shell-operator/pkg/app.Version=$shellOpVer' -X 'github.com/flant/addon-operator/pkg/app.Version=dev-refs/pull/355/merge-d33fc56c-2022.12.21_12:08:37'"              -tags use_libjq              -o addon-operator              ./cmd/addon-operator
#54 3059.1 # github.com/flant/addon-operator/cmd/addon-operator
#54 3059.1 /usr/local/go/pkg/tool/linux_arm/link: running gcc failed: exit status 1
#54 3059.1 collect2: fatal error: …
```

fix: cannot find ld

---

pkg/helm/helm.go
pkg/helm/helm3lib/helm3lib.go
pkg/helm/helm3lib/helm3lib_test.go

This PR prevents instantiating the REST client multiple times. In our current configuration, helm discovery actively allocates memory, which makes GC executions more frequent. The full description can be found [here](https://github.com/kubernetes/cli-runtime/blob/4e17abf5754235e5f3adec6b5fcb71a1b6a504d7/pkg/genericclioptions/config_flags.go#L115-L118).
Benchmark results for getting the REST client with the previously used env getter and the new persistent getter:
```
goos: darwin
goarch: amd64
pkg: github.com/flant/addon-operator/pkg/helm/helm3lib
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkRESTMapper/Env_client-12                   1413            790653 ns/op          183872 B/op       1939 allocs/op
BenchmarkRESTMapper/Persistent_client-12        44701933             27.69 …
```

feat: Persist helm3lib Kubernetes clients

---

go.mod
go.sum
pkg/helm_resources_manager/helm_resources_manager_test.go
pkg/helm_resources_manager/resources_monitor.go

Helm resource monitor only checks wether objects exist in the cluster or not. Now it uses a dynamic client but only extracts the names of objects. With the metadata client, addon-operator can only get the information needed to make a decision.
In the standby node, the resource monitor is 1/3 of all allocations.
Before:
After (during converge):
https://pkg.go.dev/k8s.io/client-go/metadata

List only metadata in resource monitor

---

pkg/module_manager/module_manager_test.go
pkg/utils/values_patch_test.go
pkg/values/validation/defaulting.go
pkg/values/validation/defaulting_test.go
pkg/values/validation/validator_test.go

Fixing a panic in runtime
Example of the panic message:
```
{"binding":"kubernetesSynchronization","binding.name":"values","event.type":"OperatorStartup","hook":"get_values.py","hook.type":"module","level":"info","module":"op-monitoring","msg":"ModuleHookRun task for Synchronization of 'main' group binding, trigger is OperatorStartup","queue":"monitoring","task.flow":"start","task.id":"2ed74914-7430-4921-aa8b-e5491d1eaa18","time":"2023-09-02T16:51:40Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2e955cb]
goroutine 16835 [running]:
github.com/flant/addon-operator/pkg/values/validation.ApplyDefaults({0x3972340?, 0xc0005bb0b0?}, 0xc005170480) …
```

Fix panic on defaulting an array without items schema

---

pkg/addon-operator/operator.go
pkg/addon-operator/operator_test.go

Pint modules to purge, but do not purge them
Purging modules is required to delete releases for modules that were renamed or deleted in a new release.
However, because of a race between downloading modules and running installation tasks on multimaster clusters.
In the future, we need to identify and figure out how to handle this race. Users want to ensure that their modules will not be deleted.

Disable purging unknown helm releases

---

go.mod
go.sum
pkg/utils/mergemap.go
pkg/utils/mergemap_test.go
pkg/utils/values.go

The idea is to allocate less memory when the map is already a map[string]interface{} / Values type.
I decided to move the code to our repo, because
1. This is a single file with two functions, the size is not big enough 
2.  Code changes were required
3. To effectively check type aliases such as `Values`, the type should be imported and be used by the function (causing cyclo dependencies)
```
goos: darwin
goarch: amd64
pkg: github.com/peterbourgon/mergemap
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
│       old.txt       │                new.txt                │
│       sec/op        │    sec/op     vs base                 │
Mapify/Map_interface-12   45830274.000n ±  9%   2.558n ±  1%  -100.00% (p=0.000 n=20)
Mapify/Map_string-12             51.12m ± 10%   40.15m ± 16%   -21.46% …
```

Update mergemap to reduce memory allocations

---

pkg/module_manager/go_hook/patchable_values.go
pkg/module_manager/module_manager.go
pkg/utils/module_config.go
pkg/utils/values_patch.go
pkg/utils/values_patch_test.go

There are some problems with the ApplyModuleDynamicValuesPatch:
* It marshals values to json for every patch
* All patches stored as a pure interface and also marshaled every time as well
For the first issue, we can compose a patch set before applying it so all the values struct will be marshaled only once for all patches. For the second problem, we can store an object we want to add / change as a raw json message, so the patch is marshaled only once when returned (or not marshalled at all for python / bash hooks).

Dynamic values patch improvements

---

pkg/addon-operator/bootstrap.go
pkg/addon-operator/debug_server.go

Added an endpoint  "/discovery" for the "/global/*" and "/module/*" routes. 
```
$curl http://localhost:9652/discovery
GET /global/config.{format:(json|yaml)}
GET /global/list.{format:(json|yaml)}
GET /global/patches.{format:(json|yaml)}
GET /global/snapshots.{format:(json|yaml)}
GET /global/values.{format:(json|yaml)}
GET /module/list.{format:(json|yaml|text)}
GET /module/resource-monitor.{format:(json|yaml)}
GET /module/{name}/patches.json
GET /module/{name}/render
GET /module/{name}/snapshots.{format:(json|yaml)}
GET /module/{name}/{type:(config|values)}.{format:(json|yaml)}
```
Fix https://github.com/deckhouse/deckhouse/issues/5827
A new endpoint is available. Calling the endpoint returns a list of available routes "/global/*" and "/module/*".

[Addon-operator ] Add debug routes

---

pkg/kube_config_manager/config/event.go
pkg/kube_config_manager/kube_config_manager.go
pkg/module_manager/models/modules/values_layered.go
pkg/module_manager/models/modules/values_storage.go
pkg/module_manager/module_manager.go
pkg/utils/module_config.go

This pr should fix the situation when dynamically enabled modules don't get their config values applied if `enabled: true` isn't set in their configuration. Also, there were several other problems to solve like: module configs for dynamically enabled modules aren't applied at startup.
Relates to https://github.com/deckhouse/deckhouse/pull/7036.
There is a problem with dynamically enabled modules (that are launched by global hooks) not getting their kube config values applied  if `enabled: true` isn't set explicitly. It happens because HandleNewKubeConfig method doesn't count dynamically enabled modules as modules enabled by config which is partially true (enabled isn't set), but these modules still should have their config values applied and recalculated each time their configs change if …

validate all enabled modules

---

pkg/addon-operator/bootstrap.go
pkg/kube_config_manager/backend/backend.go
pkg/kube_config_manager/backend/configmap/configmap.go
pkg/kube_config_manager/kube_config_manager.go
pkg/module_manager/loader/fs/fs.go
pkg/module_manager/loader/loader.go
pkg/module_manager/models/modules/events/events.go
pkg/module_manager/models/moduleset/moduleset.go
pkg/module_manager/models/moduleset/moduleset_test.go
pkg/module_manager/module_manager.go

Changes:
A lot of changes related to starting/restarting/disabling a module without restarting addon-operator.
With this PR we can provide a way of reloading (restarting its life cycle like disabling and deregistering its hooks, reloading its configuration and re-run the module)  a single module without restarting addon-operator.

[addon-operator] add module reregister

---

pkg/module_manager/models/modules/basic.go
pkg/module_manager/module_manager.go

This pr introduces an additional module state: `HooksDisabled`. In some situations it makes sense to disable a module hooks (mostly before deleting or when updating the module) and this state would allow reflecting the module status appropriately. 
Thir pr adds an additional module state `HooksDisabled` and updates a module state accordingly when the moduleManager's `DisableModuleHooks` method is invocated.

add dedicated basic module status - hooks disabled

---

pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/hook_storage.go
pkg/module_manager/module_manager.go
pkg/module_manager/module_manager_hooks.go

Adds additional boolean status field `controllersReady` to HooksStorage and uses it to decide if it's OK to run a module's hooks.
It prevents a panic in a rare situation when HandleKubeEvent/HandleScheduleEvent is evoked for a module before the module's hooks get their HookControllers set.

make sure all hooks have a hook controller set

---

go.mod
go.sum
pkg/addon-operator/operator.go
pkg/kube_config_manager/kube_config_manager_test.go
pkg/utils/values.go
pkg/utils/values_test.go

The camelCase to kebab-case string conversion function is updated to use "github.com/ettle/strcase" package instead of local implementation. It should allow converting module names containing digits more correctly.
It updates the way we convert camelCased strings to kebab-cased. At now, if we have something like 'l2-load-balancer' in kebab-case, after converting to camelCase and back it ends up with 'l-2-load-balancer'.

fix camelCase to kebab-case conversion

---

pkg/addon-operator/operator.go
pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/events/events.go
pkg/module_manager/module_manager.go

Following changes:
- Two new module events were added: ModuleStateChanged and ModuleConfig changed;
- Modules got a new state field enabledScriptResults that contains the result of running the enabled script of a module. It comes in handy when we need to know if a module was disabled by its script or something else;
- Modules can "export" their hooks' statuses via a new method;
- Module manager got several new methods which can be used to alter a module and send a relevant event over a notification channel (like setting a module last error and updating hooks' statuses);
-  Module manager can be set to use a pre-created notification channel.
This PR provides some additional calls that can be used to provide a better view of what and when is happening to modules of the operator.

Send events at module state change

---

pkg/addon-operator/operator.go
pkg/helm/client/client.go
pkg/helm/helm.go
pkg/helm/helm3/helm3.go
pkg/helm/helm3lib/helm3lib.go
pkg/helm/helm3lib/helm3lib_test.go
pkg/helm/helm_test.go
pkg/helm/test/mock/mock.go
pkg/module_manager/module_manager.go

Make helm3/helm3lib list logic use "native" tools
* Use cmd `helm` to list releases in helm3
* Use `action.NewList` to list releases in helm3lib
* Add support for [default](https://github.com/helm/helm/blob/v3.10.3/cmd/helm/root.go#L54) `HELM_DRIVER` env
* Minor refactor of helm3 cmd args making
* Remove unused arg in `ListReleasesNames` func
Support for `HELM_DRIVER` env is necessary when deploying addon-operator to the same namespace with other apps (in namespace as a service envs, for example).
Setting different `HELM_DRIVER` in addon-operator will prevent deleting releases of other apps (non-modules).

Refactor list logic for helm3 and helm3lib

---

cmd/addon-operator/main.go
pkg/addon-operator/operator.go

This pr adds a context argument to the operator's Start method.
It should be considered as a general improvement (using context is encouraged). Also, the method could be used as a [runnable](https://github.com/kubernetes-sigs/controller-runtime/blob/2e9781e9fc6054387cf0901c70db56f0b0a63083/pkg/manager/runnable_group.go#L30) for the controller-runtime manager at start up, allowing an elegant embedding of the operator's logic.

[addon-operator] add missing context to operator

---

pkg/module_manager/module_manager.go

An additional check is added if the modules hooks have their controllers set before trying to invoke them
A module's hooks architecture is still vulnerable to the situation when hooks are registered but their hook controllers haven't been set yet. Some calls like DisableModuleHooks imply that the hooks` controllers are already in place.

fix panic if hookcontrollers aren't set when disabling the module's hooks

---

pkg/addon-operator/converge/converge.go
pkg/addon-operator/debug_server.go
pkg/addon-operator/operator.go
pkg/addon-operator/operator_test.go
pkg/addon-operator/queue.go
pkg/addon-operator/queue_test.go
pkg/kube_config_manager/backend/backend.go
pkg/kube_config_manager/backend/configmap/configmap.go
pkg/kube_config_manager/kube_config_manager.go
pkg/kube_config_manager/kube_config_manager_test.go
pkg/module_manager/models/hooks/dependency.go
pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/global.go
pkg/module_manager/module_manager.go
pkg/module_manager/scheduler/extenders/dynamically_enabled/dynamic.go
pkg/module_manager/scheduler/extenders/dynamically_enabled/dynamic_test.go
pkg/module_manager/scheduler/extenders/extenders.go
pkg/module_manager/scheduler/extenders/kube_config/kube_config.go
pkg/module_manager/scheduler/extenders/script_enabled/script.go
pkg/module_manager/scheduler/extenders/script_enabled/script_test.go
pkg/module_manager/scheduler/extenders/script_enabled/testdata/402-ingress-nginx/enabled
pkg/module_manager/scheduler/extenders/static/static.go
pkg/module_manager/scheduler/node/mock/node_mock.go
pkg/module_manager/scheduler/node/node.go
pkg/module_manager/scheduler/node/node_test.go
pkg/module_manager/scheduler/scheduler.go
pkg/module_manager/scheduler/scheduler_test.go
pkg/task/hook_metadata.go

Some general improvements related to how ModuleScheduler's graph is operated.

remove retro status

---

pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/values_storage.go

When building configuration files, do not take values ​​from values.yaml files
The modules are configured in one place, uniformly, through value management. There is no need to control the process of merging changes at different levels.
Closed: [deckhouse#8810](https://github.com/deckhouse/deckhouse/issues/8810)
BREAKING CHANGES:
`values.yaml` in the root of a module are no longer considered as ConfigValues for a module, only as Values

[addon-operator] feat: change behavior for statusValues

---

pkg/module_manager/scheduler/extenders/dynamically_enabled/dynamic.go
pkg/module_manager/scheduler/extenders/error/permanent.go
pkg/module_manager/scheduler/extenders/extenders.go
pkg/module_manager/scheduler/extenders/kube_config/kube_config.go
pkg/module_manager/scheduler/extenders/script_enabled/script.go
pkg/module_manager/scheduler/extenders/script_enabled/script_test.go
pkg/module_manager/scheduler/extenders/static/static.go
pkg/module_manager/scheduler/scheduler.go
pkg/module_manager/scheduler/scheduler_test.go

Fix scheduler's errors handling
We want to have a kind of filter error that would not stop the module manager and could be passed to an extender.
Scheduler will stop only on permanent errors

Fix extender errors handling

---

pkg/module_manager/module_manager.go
pkg/module_manager/scheduler/extenders/mock/extenders_mock.go
pkg/module_manager/scheduler/scheduler.go
pkg/module_manager/scheduler/scheduler_test.go

Update error logging and Module Scheduler logic.
This pr adds extra error formatting for extenders' errors and slightly reworks the way terminating extenders are applied.
Currently, terminating extenders don't work correctly if they are placed anywhere in the applied extenders list, except for at the end. This Pr adds extra information to the list of the extenders that helps figure out how to use terminating extenders when filtering a module.

update scheduler logic regarding terminator extenders

---

pkg/module_manager/module_manager.go
pkg/module_manager/scheduler/scheduler.go

1. Fixed some erroneous logic in the scheduler's logic when filtering modules by a terminator extender.
2. Provided a couple of methods to get info which extender actually enabled/disabled a module.
1. To fix the aforementioned bug in the scheduler's logic.
2. To be able to reflect in modules' status why modules were enabled/disabled.

fix scheduler and provide get-update-by-extender method

---

pkg/module_manager/module_manager.go
pkg/module_manager/scheduler/scheduler.go

I've found a better place for setting ModulesInited flag to true.
ModulesInited flag is set to true after first graph calculation so that all information about applied extenders is available.

set ModulesInited after first graph calculation

---

pkg/addon-operator/operator.go
pkg/helm/helm.go
pkg/helm/helm3lib/helm3lib.go

If helm3lib is in use, reinit its action configuration every time a global hook provokes reconverge of all modules, cause we need to refresh helm's client capabilities in case of such a global change like kubernetes version upgrade.
We need it to keep helm's client capabilities list up-to-date.

reinit helm3lib action config on global hook module reload

---

pkg/addon-operator/converge/converge.go
pkg/addon-operator/operator.go
pkg/addon-operator/queue.go
pkg/addon-operator/queue_test.go
pkg/app/app.go
pkg/module_manager/models/modules/synchronization_state.go
pkg/module_manager/module_manager.go
pkg/module_manager/scheduler/node/node.go
pkg/module_manager/scheduler/scheduler.go
pkg/module_manager/scheduler/scheduler_test.go
pkg/task/hook_metadata.go
pkg/task/task.go

`ModuleRun` tasks and corresponding `ModuleHookRun` tasks for modules of the same order (weight) are executed `in parallel` in `parallel` queues. There are 10 `parallel` queues by default in the operator's queue set.
This pr adds new type of tasks - `ParallelModuleRun`. A task of this type represents a group of smaller tasks with the same order/weight of `ModuleRun` and `ModuleHookRun` types. These subordinate tasks are executed in parallel pre-created named `parallel_queue_x` queues and all the results and errors are propagated back to the  corresponding `ParallelModuleRun` task that updates its status accordingly.

Execute ModuleRun tasks of the same weight in parallel

---

pkg/helm_resources_manager/helm_resources_manager.go
pkg/helm_resources_manager/resources_monitor.go

refactor resource monitor and fix module name empty error

[addon-operator] Fix/module name

---

.golangci.yaml
go.mod
pkg/addon-operator/ensure_crds.go
pkg/addon-operator/operator_test.go
pkg/utils/values_test.go

Before installing crd into a cluster, we need to compare it with the existing one. Previously, we only compared spec and one of the labels. Now we will compare spec, the full set of labels and annotations.
In order to backup the CRD cluster, we will install certain labels on the necessary resources. To be able to install labels, we need to check their presence in the cluster. So as not to delete them during the next update.

fix: compare crd spec, labels and annotations before update

---

cmd/addon-operator/main.go
go.mod
go.sum
pkg/addon-operator/admission_http_server.go
pkg/module_manager/models/modules/basic.go

Addon operator minor refactoring
Bump shell operator. It fixes hooks output in JSON (LOG_PROXY_HOOK_JSON)
Bump logger lib. It adds log.Err() method to replace slog.String("error",err.Error()). Replace old methods for new.

bump logger and shell operator

---

pkg/addon-operator/operator.go
pkg/module_manager/module_manager.go
pkg/module_manager/scheduler/extenders/extenders.go
pkg/module_manager/scheduler/extenders/mock/extenders_mock.go
pkg/module_manager/scheduler/extenders/script_enabled/script.go
pkg/module_manager/scheduler/extenders/script_enabled/script_test.go
pkg/module_manager/scheduler/node/node.go
pkg/module_manager/scheduler/scheduler.go
pkg/module_manager/scheduler/scheduler_test.go
pkg/task/hook_metadata.go

Enhances the scheduler to support an additional type of extenders which can alter the graph's structure with topological hints, implementing tighter dependency (comparing to weight-based dependency) between vertices/modules.
Provides two new extender types: 
Stateful extender (instead of Ressetable extender) is a type of extenders that requires to have the current state of vertices (during the calculation) in order to make a decision if a module has to be enabled/disabled (for example, script enabled extender works this way. This state is shared among all Stateful extenders meaning that two or more extenders are able to follow the changes other extenders apply when filtering.
Topological extender, provides additional connections between vertices by means of `GetTopologicalHints` method. …

[scheduler] add topological extender type

---

.golangci.yaml
pkg/addon-operator/bootstrap.go
pkg/addon-operator/operator.go
pkg/helm/helm3/helm3.go
pkg/helm/helm3lib/helm3lib.go
pkg/helm/post_renderer/post_renderer.go
pkg/kube_config_manager/backend/configmap/configmap.go
pkg/module_manager/loader/fs/fs.go
pkg/module_manager/models/hooks/kind/batch_hook.go
pkg/module_manager/models/hooks/kind/gohook.go
pkg/module_manager/models/hooks/kind/shellhook.go
pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/global.go
pkg/module_manager/module_manager.go
pkg/task/hook_metadata.go
pkg/utils/fswalk.go
pkg/utils/loader.go
pkg/utils/module_list.go
pkg/utils/stdliblogtolog/adapter.go
pkg/values/validation/schemas.go

[ci] add nonamedreturns linter

---

pkg/addon-operator/operator.go

Adds sending module events for all disabled modules when doing first converge. This way we can update modules' states and correctly reflect reasons why the modules were disabled.

refresh states of disabled modules on first converge

---

pkg/addon-operator/debug_server.go
pkg/module_manager/models/modules/helm.go
pkg/module_manager/module_manager.go

After we return nil helm module, we must not to use render (because of nil).
Added new error and handle it, where it needs
Inside touched files:
Add errors wrapping
Replace global logger with local logger

[addon-operator] fix nil, add error handling, fix logger

---

pkg/module_manager/models/hooks/kind/shellhook.go
pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/global.go

Updates running shellhooks logic in a way that allows running a module's python hooks (*.py) with a custom python version, located in the `/module_path/hooks/venv` directory.
If a module has python hooks, but doesn't provide custom python instance in the `/module_path/hooks/venv` directory`, the hooks are executed by the system python instance and a warning is thrown.
Closes https://github.com/deckhouse/deckhouse/issues/12311

[shell-hooks] consider python vevn when running python scripts

---

pkg/helm/helm3/helm3.go
pkg/helm/helm3lib/helm3lib.go
pkg/module_manager/environment_manager/mount.go
pkg/module_manager/models/modules/global.go
pkg/module_manager/models/modules/helm.go

Use `force` update to replace resources instead of making three way merge. Module's templates is a source of truth and we have to keep objects clear, instead of merging with a cluster changes
Sort `enabledModules` and `apiVersion`. These values are used in charts, so they trigger release deploy every time, even values are not changed
**BREAKING CHANGES**
Modules will not keep resource changes made manually in a cluster anymore.

Use force while upgrade templates

---

pkg/helm/client/client.go
pkg/helm/helm3/helm3.go
pkg/helm/helm3lib/helm3lib.go
pkg/helm/helm3lib/helm3lib_test.go
pkg/helm/helm_test.go
pkg/helm/test/mock/mock.go
pkg/module_manager/models/modules/helm.go

Transferring the release checksum storage from variables to labels
Transfer the storage of checksums from environment variables to release tags

feat: add GetReleaseChecksum method and update UpgradeRelease signature

---

pkg/module_manager/models/modules/basic.go

Adding information about the module and the name of Hook to conclusion error, if it occurs when the hook is registered
Only adding small information to the output of errors

feat: improve error message for invalid module hook configuration

---

pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/helm.go
pkg/module_manager/module_manager.go

When ModuleConfig maintenance mod in NoResourceReconcillation
Set to helm release value `"maintenance.deckhouse.io/no-resource-reconcillation": true` when all resources applied
In next reconcile (for example after restart addon-operator), it looks that release value exists and equals `true`, if it was - stop reconcile helm release.
If we delete resource from corresponding Module and restart Addop-Operator
Resource will be recreated
If we delete resource from corresponding Module and restart Addop-Operator
Resource will not recreated

[addon-operator] 1.6 maintenance mode restart fix 

---

.github/workflows/build.yaml
.github/workflows/tests.yaml
Dockerfile
go.mod
go.sum
pkg/helm/client/client.go
pkg/helm/helm3/helm3.go
pkg/helm/helm3lib/helm3lib.go
pkg/module_manager/models/modules/basic.go
pkg/module_manager/models/modules/helm.go
pkg/module_manager/module_manager.go

When ModuleConfig maintenance mod in NoResourceReconcillation
Set to helm release label `"maintenance.deckhouse.io/no-resource-reconcillation": true` when all resources applied
In next reconcile (for example after restart addon-operator), it looks that release label exists and equals `true`, if it was - stop reconcile helm release.
If we delete resource from corresponding Module and restart Addop-Operator
Resource will be recreated
If we delete resource from corresponding Module and restart Addop-Operator
Resource will not recreated

[addon-operator] fix/maintenance mode restart fix

---

pkg/module_manager/go_hook/filter_result.go
pkg/module_manager/go_hook/filter_result_test.go

Now we return more verbose error when types does not match

[addon-operator] Add verbosity to unmarshal error

---

pkg/module_manager/models/modules/values_storage.go
pkg/values/validation/schemas.go

Modules(like pod-reloader) may [have no properties](https://github.com/deckhouse/pod-reloader/blob/main/openapi/values.yaml) in values.yaml, we skipped such modules and it causes validation problem.
The problem was not revealed before because it happens only if you delete a module(remove old injection on fs)
```
1. ModuleRun:parallel_queue_1:pod-reloader:doStartup:OperatorStartup:failures 19:run helm install: check helm values: 1 error occurred:
* podReloader.registry is a forbidden property
```
And result values are override after recalculation, so use static values
Fixes the registry injection

[fix] inject module registry to values

---

pkg/module_manager/module_manager.go
pkg/task/tasks/converge-modules/task.go

Defer stopping Kubernetes monitors for modules scheduled to be disabled. In converge phase, only disable schedule bindings; keep Kubernetes watchers alive until `afterDeleteHelm` runs during `DeleteModule`. Full hook disabling still happens right after `afterDeleteHelm`.
- Previously, converge disabled all module hooks (including Kubernetes monitors) immediately for modules in `ModulesToDisable`. As a side effect, `afterDeleteHelm` hooks received empty snapshots because monitors were already stopped.
- This PR:
- Changes converge to disable only schedule bindings for modules to disable.
- Leaves Kubernetes monitors running so `DeleteModule` can execute `afterDeleteHelm` with populated snapshots.
- Keeps the existing cleanup: `DisableModuleHooks` is still invoked in `DeleteModule` right …

Don't disable monitors before after delete hook run

---

pkg/module_manager/models/modules/global.go

Fixed duplicate log messages during addon-operator startup caused by incorrect logging message in searchGlobalBatchHooks function.
This PR fixes a logging issue in pkg/module_manager/models/modules/global.go where the searchGlobalBatchHooks function was incorrectly logging "Found global shell hooks in dir" instead of "Found global batch hooks in dir".

[addon-operator] remove search hooks log duplicates

---

go.mod
go.sum
pkg/addon-operator/metrics.go
pkg/addon-operator/operator_test.go
pkg/addon-operator/queue.go
pkg/addon-operator/queue_test.go
pkg/module_manager/module_manager.go
pkg/task/queue/queue.go
pkg/task/service/converge.go

Replaced synchronization primitives with atomics to eliminate deadlock potential
Introduced a thread-safe status management system with TaskQueueStatus
Added deadlock prevention mechanisms in queue operations

[fix] Fix possibly deadlock
